package StremAPI;

import java.util.Arrays;
import java.util.List;

public class StreamDemo {
    public static void main(String[] args) {
        List<Integer> list = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
        System.out.println("Even numbers");
        list.stream().filter(i -> i % 2 == 0).forEach(System.out::println);
        System.out.println("Square of numbers");
        list.stream().map(i -> i * i).forEach(System.out::println);
        System.out.println("Sorted numbers");
        list.stream().sorted().forEach(System.out::println);
        System.out.println("Limit of numbers");
        list.stream().limit(5).forEach(System.out::println);
        System.out.println("Skip of numbers");
        list.stream().skip(5).forEach(System.out::println);
        System.out.println("Distinct of numbers");
        list.stream().distinct().forEach(System.out::println);
        System.out.println("Count of numbers");
        list.stream().count();
        System.out.println("Min of numbers");
        list.stream().min(Integer::compare).get();
        System.out.println("Max of numbers");
        list.stream().max(Integer::compare).get();
        System.out.println("Sum of numbers");
        list.stream().reduce(0, (a, b) -> a + b);
        System.out.println("Average of numbers");
        list.stream().mapToInt(i -> i).average().getAsDouble();
        System.out.println("Sum of numbers");
        list.stream().mapToInt(i -> i).sum();
        System.out.println("Any match of numbers");
        list.stream().anyMatch(i -> i % 2 == 0);
        System.out.println("All match of numbers");
        list.stream().allMatch(i -> i % 2 == 0);
        System.out.println("None match of numbers");
        list.stream().noneMatch(i -> i % 2 == 0);
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
        list.stream().reduce((a, b) -> b).get();
        System.out.println("Find any of numbers");
        list.stream().findAny().get();
        System.out.println("Find first of numbers");
        list.stream().findFirst().get();
        System.out.println("Find last of numbers");
    }
}
